<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Validator\AvailabilityValidator' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
include_once \dirname(__DIR__, 4).'/src/Validator/AvailabilityValidator.php';

return $this->privates['App\\Validator\\AvailabilityValidator'] = new \App\Validator\AvailabilityValidator(($this->privates['App\\Repository\\UnavailabilityRepository'] ?? $this->load('getUnavailabilityRepositoryService.php')));
